ms-vscode.cmake-tools
twxs.cmake
slevesque.shader
mkhl.direnv
maximedenes.vscoq
vspacecode.vspacecode
vspacecode.whichkey
banacorn.agda-mode
nwolverson.language-purescript
nwolverson.ide-purescript
betterthantomorrow.calva
haskell.haskell
justusadam.language-haskell
jnoortheen.nix-ide
matklad.rust-analyzer
kahole.magit
asvetliakov.vscode-neovim
llvm-vs-code-extensions.vscode-clangd
vadimcn.vscode-lldb
dhall.dhall-lang
dhall.vscode-dhall-lsp-server
tiehuis.zig

